# Copyright 2021 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#BERT-Large, max seq length 512

### Input
train_input:
    data_processor: BertTfRecordsProcessor
    data_dir: '/cb/ml/language/datasets/TRC2/trc2_msl512_finvocab'
    vocab_file: '/cb/home/sanjana/wells_fargo/FinVocab-Uncased.txt'
    max_sequence_length: 512
    max_predictions_per_seq: 80  # maximum number of masked LM predictions per sequence. Fixed to 20 for now
    batch_size: 256

eval_input:
    data_processor: BertTfRecordsProcessor
    data_dir: '/cb/ml/language/datasets/TRC2/trc2_msl512_finvocab_validate'
    vocab_file: '/cb/home/sanjana/wells_fargo/FinVocab-Uncased.txt'
    max_sequence_length: 512     # fixed to 128 for LM for now
    max_predictions_per_seq: 80  # maximum number of masked LM predictions per sequence. Fixed to 20 for now
    batch_size: 256

model:
    # Embedding
    hidden_size: 1024
    use_position_embedding: True
    use_segment_embedding: True
    position_embedding_type: 'learned' # {'learned', 'fixed'}
    max_position_embeddings: 512
    share_embedding_weights: True

    # Encoder
    num_hidden_layers: 8
    dropout_rate: 0.1
    layer_norm_epsilon: 1e-5

    # Encoder - Attention
    num_heads: 16
    attention_dropout_rate: 0.1

    # Encoder - ffn
    filter_size: 4096
    encoder_nonlinearity: 'gelu'
    use_ffn_bias: True

    # Task-specific
    mlm_loss_weight: 0.019 # should be 0.058 if training with max seq length 128; 0.019 if training with max seq length 512

    mixed_precision: True
    boundary_casting: False
    tf_summary: False

### Optimization
optimizer:
    optimizer_type: 'adamw' # {'sgd', 'momentum', 'adam', 'adamw'}
    weight_decay_rate: 0.01
    epsilon: 1e-6
    max_gradient_norm: 1.0
    disable_lr_steps_reset: True
    learning_rate:
        - steps: 10000
          scheduler: 'Linear'
          initial_learning_rate: 0.0
          end_learning_rate: 0.0001
        - scheduler: 'Linear'
          initial_learning_rate: 0.0001
          end_learning_rate: 0.0
          steps: 1000000
    loss_scaling_factor: 'dynamic'

runconfig:
    save_summary_steps: 100
    save_checkpoints_steps: 50000
    keep_checkpoint_max: 0
    max_steps: 700000
    enable_distributed: False
    model_dir: 'model_dir'
    cs_ip: 10.254.7.160 
    mode: 'train'
